// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtrxfzaitocellyuhjdb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0cnhmemFpdG9jZWxseXVoamRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5OTc2OTIsImV4cCI6MjA2MjU3MzY5Mn0.Nu1RrDGesmTfjKdVfN41acpr5HJowdkK-9rcKTEW4No"
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);